env:
  browser: true
parserOptions:
  ecmaVersion: 8
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - off
  semi:
    - error
    - always
  no-console:
    - off
  no-undef:
    - warn
  no-unused-vars:
    - warn
